server:
  port: 8675
  
spring:
  application:
    name: gateway-service
    
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    lease-expiration-duration-in-seconds: 10
    lease-renewal-interval-in-seconds: 5
    
    
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000
zuul:
  routes:
    users:
      path: /users/**
      service-id: user-service
      strip-prefix: false
    cats:
      path: /cats/**
      service-id: cat-service
      strip-prefix: false