server:
  port: 8890
  
spring:
  application:
    name: cat-service 

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    lease-expiration-duration-in-seconds: 10
    lease-renewal-interval-in-seconds: 5
    
feign:
  hystrix:
    enabled: true